import "./scripts/spoilers.js";
import "./scripts/price.js";
import "./scripts/more.js";
import "./scripts/filter.js";
import "./scripts/products-grid.js";
import "./scripts/prices.js";
import "./scripts/radios.js";
import "./scripts/actions.js";
import "./scripts/products-more.js";
